/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtocolosHdr28RouteImport } from './routes/protocolos.hdr28'
import { Route as ProtocolosAscensaoFemininaRouteImport } from './routes/protocolos.ascensao-feminina'
import { Route as ProtocolosAscendaRouteImport } from './routes/protocolos.ascenda'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosHdr28Route = ProtocolosHdr28RouteImport.update({
  id: '/protocolos/hdr28',
  path: '/protocolos/hdr28',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosAscensaoFemininaRoute =
  ProtocolosAscensaoFemininaRouteImport.update({
    id: '/protocolos/ascensao-feminina',
    path: '/protocolos/ascensao-feminina',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtocolosAscendaRoute = ProtocolosAscendaRouteImport.update({
  id: '/protocolos/ascenda',
  path: '/protocolos/ascenda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/sobre': typeof SobreRoute
  '/protocolos/ascenda': typeof ProtocolosAscendaRoute
  '/protocolos/ascensao-feminina': typeof ProtocolosAscensaoFemininaRoute
  '/protocolos/hdr28': typeof ProtocolosHdr28Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/sobre': typeof SobreRoute
  '/protocolos/ascenda': typeof ProtocolosAscendaRoute
  '/protocolos/ascensao-feminina': typeof ProtocolosAscensaoFemininaRoute
  '/protocolos/hdr28': typeof ProtocolosHdr28Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/sobre': typeof SobreRoute
  '/protocolos/ascenda': typeof ProtocolosAscendaRoute
  '/protocolos/ascensao-feminina': typeof ProtocolosAscensaoFemininaRoute
  '/protocolos/hdr28': typeof ProtocolosHdr28Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/depoimentos'
    | '/sobre'
    | '/protocolos/ascenda'
    | '/protocolos/ascensao-feminina'
    | '/protocolos/hdr28'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/depoimentos'
    | '/sobre'
    | '/protocolos/ascenda'
    | '/protocolos/ascensao-feminina'
    | '/protocolos/hdr28'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/depoimentos'
    | '/sobre'
    | '/protocolos/ascenda'
    | '/protocolos/ascensao-feminina'
    | '/protocolos/hdr28'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  SobreRoute: typeof SobreRoute
  ProtocolosAscendaRoute: typeof ProtocolosAscendaRoute
  ProtocolosAscensaoFemininaRoute: typeof ProtocolosAscensaoFemininaRoute
  ProtocolosHdr28Route: typeof ProtocolosHdr28Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos/hdr28': {
      id: '/protocolos/hdr28'
      path: '/protocolos/hdr28'
      fullPath: '/protocolos/hdr28'
      preLoaderRoute: typeof ProtocolosHdr28RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos/ascensao-feminina': {
      id: '/protocolos/ascensao-feminina'
      path: '/protocolos/ascensao-feminina'
      fullPath: '/protocolos/ascensao-feminina'
      preLoaderRoute: typeof ProtocolosAscensaoFemininaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos/ascenda': {
      id: '/protocolos/ascenda'
      path: '/protocolos/ascenda'
      fullPath: '/protocolos/ascenda'
      preLoaderRoute: typeof ProtocolosAscendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  SobreRoute: SobreRoute,
  ProtocolosAscendaRoute: ProtocolosAscendaRoute,
  ProtocolosAscensaoFemininaRoute: ProtocolosAscensaoFemininaRoute,
  ProtocolosHdr28Route: ProtocolosHdr28Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
